services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "127.0.0.1:${WEB_PORT}:8069" # Solo acceso local por seguridad
    environment:
      - HOST=db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:15
    ports:
      - "127.0.0.1:${DB_PORT}:5432"  # Solo acceso local por seguridad
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    
volumes:
  odoo-web-data:
  odoo-db-data:
